name: DefKorns Mods
title: DefKorns | Mod repository
description: This is the hq for all my mods.
tags:
  - defkorns
  - mods
  - hakchi
  - project lunar
  - project eris
  - modmyclassic
  - mini
  - themes
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: defkorns@gmail.com
# See: https://disqus.com/
disqus_username: defkorns
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
